version: "3.9"
services:
  node:
    image: node:19.0
    user: node
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    working_dir: /app
    ports:
      - 3000:3000
    # command: bash -c "tail -F anything"
    command: bash -c "npm install && npm run dev"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: "${MYSQL_HOST}"
      PMA_USER: "${MYSQL_USER}"
      PMA_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - 8080:80

volumes:
  mysql:
